{"level":"error","message":"Error adding addon: Failed to fetch manifest: 404","stack":"Error: Failed to fetch manifest: 404\n    at /home/bb/Desktop/dark/stremioadmindark/app.js:534:19\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-01-24 17:36:19"}
{"level":"error","message":"Error adding addon: Failed to fetch manifest: 404","stack":"Error: Failed to fetch manifest: 404\n    at /home/bb/Desktop/dark/stremioadmindark/app.js:258:19\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-01-24 17:53:39"}
{"level":"error","message":"Error adding addon: Cannot read properties of undefined (reading 'find')","stack":"TypeError: Cannot read properties of undefined (reading 'find')\n    at /home/bb/Desktop/dark/stremioadmindark/app.js:335:33","timestamp":"2025-01-24 19:22:11"}
{"address":"::","code":"EADDRINUSE","errno":-98,"level":"error","message":"Uncaught Exception: listen EADDRINUSE: address already in use :::3001","port":3001,"stack":"Error: listen EADDRINUSE: address already in use :::3001\n    at Server.setupListenHandle [as _listen2] (node:net:1811:16)\n    at listenInCluster (node:net:1859:12)\n    at Server.listen (node:net:1947:7)\n    at Function.listen (/home/bb/Desktop/stremio/dark/stremioadmindark/node_modules/express/lib/application.js:635:24)\n    at /home/bb/Desktop/stremio/dark/stremioadmindark/app.js:562:9","syscall":"listen","timestamp":"2025-01-24 21:20:11"}
{"level":"error","message":"Error adding addon: Cannot read properties of undefined (reading 'find')","stack":"TypeError: Cannot read properties of undefined (reading 'find')\n    at /home/bb/Desktop/stremio/dark/stremioadmindark/app.js:333:33\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-01-25 07:16:36"}
{"level":"error","message":"Error adding addon: Cannot read properties of undefined (reading 'find')","stack":"TypeError: Cannot read properties of undefined (reading 'find')\n    at /home/bb/Desktop/stremio/dark/stremioadmindark/app.js:333:33\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-01-25 07:18:05"}
{"level":"error","message":"Error adding addon: Cannot read properties of undefined (reading 'find')","stack":"TypeError: Cannot read properties of undefined (reading 'find')\n    at /home/bb/Desktop/stremio/dark/stremioadmindark/app.js:333:33\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-01-25 07:19:13"}
{"code":"EAI_AGAIN","errno":"EAI_AGAIN","level":"error","message":"request to https://api.strem.io/api/logout failed, reason: getaddrinfo EAI_AGAIN api.strem.io","stack":"FetchError: request to https://api.strem.io/api/logout failed, reason: getaddrinfo EAI_AGAIN api.strem.io\n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-01-25 09:21:58","type":"system"}
{"code":"EAI_AGAIN","errno":"EAI_AGAIN","level":"error","message":"request to https://api.strem.io/api/logout failed, reason: getaddrinfo EAI_AGAIN api.strem.io","stack":"FetchError: request to https://api.strem.io/api/logout failed, reason: getaddrinfo EAI_AGAIN api.strem.io\n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-01-25 09:21:58","type":"system"}
{"code":"ETIMEDOUT","errno":"ETIMEDOUT","level":"error","message":"request to https://api.strem.io/api/login failed, reason: ","stack":"FetchError: request to https://api.strem.io/api/login failed, reason: \n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-01-25 09:22:25","type":"system"}
{"code":"ETIMEDOUT","errno":"ETIMEDOUT","level":"error","message":"request to https://api.strem.io/api/login failed, reason: ","stack":"FetchError: request to https://api.strem.io/api/login failed, reason: \n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-01-25 09:22:25","type":"system"}
{"code":"ETIMEDOUT","errno":"ETIMEDOUT","level":"error","message":"request to https://api.strem.io/api/login failed, reason: ","stack":"FetchError: request to https://api.strem.io/api/login failed, reason: \n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-01-25 09:22:25","type":"system"}
{"code":"ETIMEDOUT","errno":"ETIMEDOUT","level":"error","message":"request to https://api.strem.io/api/login failed, reason: ","stack":"FetchError: request to https://api.strem.io/api/login failed, reason: \n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-01-25 09:22:25","type":"system"}
{"code":"ETIMEDOUT","errno":"ETIMEDOUT","level":"error","message":"request to https://api.strem.io/api/login failed, reason: ","stack":"FetchError: request to https://api.strem.io/api/login failed, reason: \n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-01-25 09:22:47","type":"system"}
{"code":"ETIMEDOUT","errno":"ETIMEDOUT","level":"error","message":"request to https://api.strem.io/api/login failed, reason: ","stack":"FetchError: request to https://api.strem.io/api/login failed, reason: \n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-01-25 09:22:47","type":"system"}
{"code":"ETIMEDOUT","errno":"ETIMEDOUT","level":"error","message":"request to https://api.strem.io/api/login failed, reason: ","stack":"FetchError: request to https://api.strem.io/api/login failed, reason: \n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-01-25 09:22:47","type":"system"}
{"code":"ETIMEDOUT","errno":"ETIMEDOUT","level":"error","message":"request to https://api.strem.io/api/login failed, reason: ","stack":"FetchError: request to https://api.strem.io/api/login failed, reason: \n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-01-25 09:22:47","type":"system"}
{"code":"ETIMEDOUT","errno":"ETIMEDOUT","level":"error","message":"request to https://api.strem.io/api/login failed, reason: ","stack":"FetchError: request to https://api.strem.io/api/login failed, reason: \n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-01-25 09:23:22","type":"system"}
{"code":"ETIMEDOUT","errno":"ETIMEDOUT","level":"error","message":"request to https://api.strem.io/api/login failed, reason: ","stack":"FetchError: request to https://api.strem.io/api/login failed, reason: \n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-01-25 09:23:22","type":"system"}
{"code":"EAI_AGAIN","errno":"EAI_AGAIN","level":"error","message":"request to https://api.strem.io/api/login failed, reason: getaddrinfo EAI_AGAIN api.strem.io","stack":"FetchError: request to https://api.strem.io/api/login failed, reason: getaddrinfo EAI_AGAIN api.strem.io\n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-01-25 09:24:00","type":"system"}
{"code":"EAI_AGAIN","errno":"EAI_AGAIN","level":"error","message":"request to https://api.strem.io/api/login failed, reason: getaddrinfo EAI_AGAIN api.strem.io","stack":"FetchError: request to https://api.strem.io/api/login failed, reason: getaddrinfo EAI_AGAIN api.strem.io\n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-01-25 09:24:00","type":"system"}
{"code":"ETIMEDOUT","errno":"ETIMEDOUT","level":"error","message":"request to https://api.strem.io/api/login failed, reason: ","stack":"FetchError: request to https://api.strem.io/api/login failed, reason: \n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at listOnTimeout (node:internal/timers:545:9)","timestamp":"2025-01-25 09:24:13","type":"system"}
{"code":"ETIMEDOUT","errno":"ETIMEDOUT","level":"error","message":"request to https://api.strem.io/api/login failed, reason: ","stack":"FetchError: request to https://api.strem.io/api/login failed, reason: \n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at listOnTimeout (node:internal/timers:545:9)","timestamp":"2025-01-25 09:24:13","type":"system"}
{"code":"ETIMEDOUT","errno":"ETIMEDOUT","level":"error","message":"request to https://api.strem.io/api/login failed, reason: ","stack":"FetchError: request to https://api.strem.io/api/login failed, reason: \n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at listOnTimeout (node:internal/timers:545:9)","timestamp":"2025-01-25 09:24:13","type":"system"}
{"code":"ETIMEDOUT","errno":"ETIMEDOUT","level":"error","message":"request to https://api.strem.io/api/login failed, reason: ","stack":"FetchError: request to https://api.strem.io/api/login failed, reason: \n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at listOnTimeout (node:internal/timers:545:9)","timestamp":"2025-01-25 09:24:13","type":"system"}
{"code":"ETIMEDOUT","errno":"ETIMEDOUT","level":"error","message":"request to https://api.strem.io/api/login failed, reason: ","stack":"FetchError: request to https://api.strem.io/api/login failed, reason: \n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at listOnTimeout (node:internal/timers:545:9)","timestamp":"2025-01-25 09:24:13","type":"system"}
{"code":"ETIMEDOUT","errno":"ETIMEDOUT","level":"error","message":"request to https://api.strem.io/api/login failed, reason: ","stack":"FetchError: request to https://api.strem.io/api/login failed, reason: \n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at listOnTimeout (node:internal/timers:545:9)","timestamp":"2025-01-25 09:24:13","type":"system"}
{"code":"ETIMEDOUT","errno":"ETIMEDOUT","level":"error","message":"request to https://api.strem.io/api/login failed, reason: ","stack":"FetchError: request to https://api.strem.io/api/login failed, reason: \n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-01-25 09:24:13","type":"system"}
{"code":"ETIMEDOUT","errno":"ETIMEDOUT","level":"error","message":"request to https://api.strem.io/api/login failed, reason: ","stack":"FetchError: request to https://api.strem.io/api/login failed, reason: \n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-01-25 09:24:13","type":"system"}
{"code":"ETIMEDOUT","errno":"ETIMEDOUT","level":"error","message":"request to https://api.strem.io/api/login failed, reason: ","stack":"FetchError: request to https://api.strem.io/api/login failed, reason: \n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at listOnTimeout (node:internal/timers:545:9)","timestamp":"2025-01-25 09:24:13","type":"system"}
{"code":"ETIMEDOUT","errno":"ETIMEDOUT","level":"error","message":"request to https://api.strem.io/api/login failed, reason: ","stack":"FetchError: request to https://api.strem.io/api/login failed, reason: \n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at listOnTimeout (node:internal/timers:545:9)","timestamp":"2025-01-25 09:24:13","type":"system"}
{"code":"ETIMEDOUT","errno":"ETIMEDOUT","level":"error","message":"request to https://api.strem.io/api/login failed, reason: ","stack":"FetchError: request to https://api.strem.io/api/login failed, reason: \n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at listOnTimeout (node:internal/timers:545:9)","timestamp":"2025-01-25 09:24:13","type":"system"}
{"code":"ETIMEDOUT","errno":"ETIMEDOUT","level":"error","message":"request to https://api.strem.io/api/login failed, reason: ","stack":"FetchError: request to https://api.strem.io/api/login failed, reason: \n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at listOnTimeout (node:internal/timers:545:9)","timestamp":"2025-01-25 09:24:13","type":"system"}
{"code":"ETIMEDOUT","errno":"ETIMEDOUT","level":"error","message":"request to https://api.strem.io/api/login failed, reason: ","stack":"FetchError: request to https://api.strem.io/api/login failed, reason: \n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at listOnTimeout (node:internal/timers:545:9)","timestamp":"2025-01-25 09:24:13","type":"system"}
{"code":"ETIMEDOUT","errno":"ETIMEDOUT","level":"error","message":"request to https://api.strem.io/api/login failed, reason: ","stack":"FetchError: request to https://api.strem.io/api/login failed, reason: \n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at listOnTimeout (node:internal/timers:545:9)","timestamp":"2025-01-25 09:24:13","type":"system"}
{"code":"ETIMEDOUT","errno":"ETIMEDOUT","level":"error","message":"request to https://api.strem.io/api/login failed, reason: ","stack":"FetchError: request to https://api.strem.io/api/login failed, reason: \n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-01-25 09:24:13","type":"system"}
{"code":"ETIMEDOUT","errno":"ETIMEDOUT","level":"error","message":"request to https://api.strem.io/api/login failed, reason: ","stack":"FetchError: request to https://api.strem.io/api/login failed, reason: \n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-01-25 09:24:13","type":"system"}
{"code":"ETIMEDOUT","errno":"ETIMEDOUT","level":"error","message":"request to https://api.strem.io/api/login failed, reason: ","stack":"FetchError: request to https://api.strem.io/api/login failed, reason: \n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-01-25 09:26:13","type":"system"}
{"code":"ETIMEDOUT","errno":"ETIMEDOUT","level":"error","message":"request to https://api.strem.io/api/login failed, reason: ","stack":"FetchError: request to https://api.strem.io/api/login failed, reason: \n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-01-25 09:26:13","type":"system"}
{"code":"ETIMEDOUT","errno":"ETIMEDOUT","level":"error","message":"request to https://api.strem.io/api/login failed, reason: ","stack":"FetchError: request to https://api.strem.io/api/login failed, reason: \n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-01-25 09:26:16","type":"system"}
{"code":"ETIMEDOUT","errno":"ETIMEDOUT","level":"error","message":"request to https://api.strem.io/api/login failed, reason: ","stack":"FetchError: request to https://api.strem.io/api/login failed, reason: \n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-01-25 09:26:16","type":"system"}
{"code":"ETIMEDOUT","errno":"ETIMEDOUT","level":"error","message":"request to https://api.strem.io/api/login failed, reason: ","stack":"FetchError: request to https://api.strem.io/api/login failed, reason: \n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-01-25 09:26:18","type":"system"}
{"code":"ETIMEDOUT","errno":"ETIMEDOUT","level":"error","message":"request to https://api.strem.io/api/login failed, reason: ","stack":"FetchError: request to https://api.strem.io/api/login failed, reason: \n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-01-25 09:26:18","type":"system"}
{"code":"ETIMEDOUT","errno":"ETIMEDOUT","level":"error","message":"request to https://api.strem.io/api/login failed, reason: ","stack":"FetchError: request to https://api.strem.io/api/login failed, reason: \n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-01-25 09:26:22","type":"system"}
{"code":"ETIMEDOUT","errno":"ETIMEDOUT","level":"error","message":"request to https://api.strem.io/api/login failed, reason: ","stack":"FetchError: request to https://api.strem.io/api/login failed, reason: \n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-01-25 09:26:22","type":"system"}
{"code":"ENOENT","errno":-2,"level":"error","message":"Error fetching users: ENOENT: no such file or directory, open '/www/wwwroot/stremioadmindark/databases/greg_at_greg.com/users.json'","path":"/www/wwwroot/stremioadmindark/databases/greg_at_greg.com/users.json","stack":"Error: ENOENT: no such file or directory, open '/www/wwwroot/stremioadmindark/databases/greg_at_greg.com/users.json'\n    at async open (node:internal/fs/promises:639:25)\n    at async Object.readFile (node:internal/fs/promises:1242:14)\n    at async readUsersDatabase (/www/wwwroot/stremioadmindark/app.js:106:18)\n    at async /www/wwwroot/stremioadmindark/app.js:397:23","syscall":"open","timestamp":"2025-01-25 09:50:38"}
{"code":"ENOENT","errno":-2,"level":"error","message":"Error reading addons: ENOENT: no such file or directory, open '/www/wwwroot/stremioadmindark/databases/greg_at_greg.com/addons.json'","path":"/www/wwwroot/stremioadmindark/databases/greg_at_greg.com/addons.json","stack":"Error: ENOENT: no such file or directory, open '/www/wwwroot/stremioadmindark/databases/greg_at_greg.com/addons.json'\n    at async open (node:internal/fs/promises:639:25)\n    at async Object.readFile (node:internal/fs/promises:1242:14)\n    at async readDatabase (/www/wwwroot/stremioadmindark/app.js:94:18)\n    at async /www/wwwroot/stremioadmindark/app.js:307:22","syscall":"open","timestamp":"2025-01-25 09:50:38"}
{"code":"ENOENT","errno":-2,"level":"error","message":"Error fetching users: ENOENT: no such file or directory, open '/www/wwwroot/stremioadmindark/databases/greg_at_greg.com/users.json'","path":"/www/wwwroot/stremioadmindark/databases/greg_at_greg.com/users.json","stack":"Error: ENOENT: no such file or directory, open '/www/wwwroot/stremioadmindark/databases/greg_at_greg.com/users.json'\n    at async open (node:internal/fs/promises:639:25)\n    at async Object.readFile (node:internal/fs/promises:1242:14)\n    at async readUsersDatabase (/www/wwwroot/stremioadmindark/app.js:106:18)\n    at async /www/wwwroot/stremioadmindark/app.js:397:23","syscall":"open","timestamp":"2025-01-25 09:50:38"}
{"code":"ENOENT","errno":-2,"level":"error","message":"Error reading addons: ENOENT: no such file or directory, open '/www/wwwroot/stremioadmindark/databases/greg_at_greg.com/addons.json'","path":"/www/wwwroot/stremioadmindark/databases/greg_at_greg.com/addons.json","stack":"Error: ENOENT: no such file or directory, open '/www/wwwroot/stremioadmindark/databases/greg_at_greg.com/addons.json'\n    at async open (node:internal/fs/promises:639:25)\n    at async Object.readFile (node:internal/fs/promises:1242:14)\n    at async readDatabase (/www/wwwroot/stremioadmindark/app.js:94:18)\n    at async /www/wwwroot/stremioadmindark/app.js:307:22","syscall":"open","timestamp":"2025-01-25 09:50:38"}
{"code":"EAI_AGAIN","errno":"EAI_AGAIN","level":"error","message":"request to https://api.strem.io/api/register failed, reason: getaddrinfo EAI_AGAIN api.strem.io","stack":"FetchError: request to https://api.strem.io/api/register failed, reason: getaddrinfo EAI_AGAIN api.strem.io\n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-01-25 13:25:45","type":"system"}
{"code":"EAI_AGAIN","errno":"EAI_AGAIN","level":"error","message":"request to https://api.strem.io/api/register failed, reason: getaddrinfo EAI_AGAIN api.strem.io","stack":"FetchError: request to https://api.strem.io/api/register failed, reason: getaddrinfo EAI_AGAIN api.strem.io\n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-01-25 13:25:48","type":"system"}
{"code":"EAI_AGAIN","errno":"EAI_AGAIN","level":"error","message":"request to https://api.strem.io/api/register failed, reason: getaddrinfo EAI_AGAIN api.strem.io","stack":"FetchError: request to https://api.strem.io/api/register failed, reason: getaddrinfo EAI_AGAIN api.strem.io\n    at ClientRequest.<anonymous> (/www/wwwroot/stremioadmindark/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-01-25 13:25:55","type":"system"}
